{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-otel-collector
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
data:
  config.yaml: |
    {{- toYaml .Values.otelCollector.config | nindent 4 }}
{{- end }}

