#!/usr/bin/env python3
"""
Proper Code Generation Domain Ontology
Using RDF/OWL with rdflib for formal ontological modeling
"""

import rdflib
from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS, OWL, XSD
import json
from pathlib import Path
from typing import Dict, Any, List, Optional


class ProperCodeGenerationOntology:
    """Proper ontological model using RDF/OWL with rdflib"""

    def __init__(self):
        # Initialize RDF graph
        self.g = Graph()

        # Define namespaces
        self.CG = Namespace("http://example.org/code-generation#")
        self.RE = Namespace("http://example.org/reverse-engineering#")
        self.CODE = Namespace("http://example.org/code#")

        # Bind namespaces
        self.g.bind("cg", self.CG)
        self.g.bind("re", self.RE)
        self.g.bind("code", self.CODE)
        self.g.bind("owl", OWL)
        self.g.bind("rdfs", RDFS)
        self.g.bind("xsd", XSD)

        # Build the ontology
        self._build_ontology()

    def _build_ontology(self):
        """Build the formal ontological structure"""

        # Define classes
        self._define_classes()

        # Define object properties
        self._define_object_properties()

        # Define data properties
        self._define_data_properties()

        # Define individuals and relationships
        self._define_individuals()

    def _define_classes(self):
        """Define ontological classes"""

        # Component class
        self.g.add((self.CG.Component, RDF.type, OWL.Class))
        self.g.add((self.CG.Component, RDFS.label, Literal("Component")))
        self.g.add(
            (
                self.CG.Component,
                RDFS.comment,
                Literal("A code component that can be discovered or generated"),
            )
        )

        # Reverse Engineering Component
        self.g.add((self.RE.ReverseEngineeringComponent, RDF.type, OWL.Class))
        self.g.add((self.RE.ReverseEngineeringComponent, RDFS.subClassOf, self.CG.Component))
        self.g.add(
            (
                self.RE.ReverseEngineeringComponent,
                RDFS.label,
                Literal("Reverse Engineering Component"),
            )
        )
        self.g.add(
            (
                self.RE.ReverseEngineeringComponent,
                RDFS.comment,
                Literal("A component discovered during reverse engineering"),
            )
        )

        # Code Generation Component
        self.g.add((self.CG.CodeGenerationComponent, RDF.type, OWL.Class))
        self.g.add((self.CG.CodeGenerationComponent, RDFS.subClassOf, self.CG.Component))
        self.g.add(
            (
                self.CG.CodeGenerationComponent,
                RDFS.label,
                Literal("Code Generation Component"),
            )
        )
        self.g.add(
            (
                self.CG.CodeGenerationComponent,
                RDFS.comment,
                Literal("A component to be generated by the code generation system"),
            )
        )

        # Method class
        self.g.add((self.CODE.Method, RDF.type, OWL.Class))
        self.g.add((self.CODE.Method, RDFS.label, Literal("Method")))
        self.g.add((self.CODE.Method, RDFS.comment, Literal("A method within a component")))

        # Context class
        self.g.add((self.CG.Context, RDF.type, OWL.Class))
        self.g.add((self.CG.Context, RDFS.label, Literal("Context")))
        self.g.add(
            (
                self.CG.Context,
                RDFS.comment,
                Literal("The context in which a component exists"),
            )
        )

        # Format class
        self.g.add((self.CG.Format, RDF.type, OWL.Class))
        self.g.add((self.CG.Format, RDFS.label, Literal("Format")))
        self.g.add((self.CG.Format, RDFS.comment, Literal("The data format of a component")))

    def _define_object_properties(self):
        """Define object properties (relationships between classes)"""

        # transformsTo - reverse engineering component transforms to code generation component
        self.g.add((self.RE.transformsTo, RDF.type, OWL.ObjectProperty))
        self.g.add((self.RE.transformsTo, RDFS.domain, self.RE.ReverseEngineeringComponent))
        self.g.add((self.RE.transformsTo, RDFS.range, self.CG.CodeGenerationComponent))
        self.g.add((self.RE.transformsTo, RDFS.label, Literal("transforms to")))

        # transformsFrom - code generation component transforms from reverse engineering component
        self.g.add((self.CG.transformsFrom, RDF.type, OWL.ObjectProperty))
        self.g.add((self.CG.transformsFrom, RDFS.domain, self.CG.CodeGenerationComponent))
        self.g.add((self.CG.transformsFrom, RDFS.range, self.RE.ReverseEngineeringComponent))
        self.g.add((self.CG.transformsFrom, RDFS.label, Literal("transforms from")))

        # hasMethod - component has methods
        self.g.add((self.CG.hasMethod, RDF.type, OWL.ObjectProperty))
        self.g.add((self.CG.hasMethod, RDFS.domain, self.CG.Component))
        self.g.add((self.CG.hasMethod, RDFS.range, self.CODE.Method))
        self.g.add((self.CG.hasMethod, RDFS.label, Literal("has method")))

        # hasContext - component exists in a context
        self.g.add((self.CG.hasContext, RDF.type, OWL.ObjectProperty))
        self.g.add((self.CG.hasContext, RDFS.domain, self.CG.Component))
        self.g.add((self.CG.hasContext, RDFS.range, self.CG.Context))
        self.g.add((self.CG.hasContext, RDFS.label, Literal("has context")))

        # hasFormat - component has a specific format
        self.g.add((self.CG.hasFormat, RDF.type, OWL.ObjectProperty))
        self.g.add((self.CG.hasFormat, RDFS.domain, self.CG.Component))
        self.g.add((self.CG.hasFormat, RDFS.range, self.CG.Format))
        self.g.add((self.CG.hasFormat, RDFS.label, Literal("has format")))

    def _define_data_properties(self):
        """Define data properties (attributes of classes)"""

        # hasName - component has a name
        self.g.add((self.CG.hasName, RDF.type, OWL.DatatypeProperty))
        self.g.add((self.CG.hasName, RDFS.domain, self.CG.Component))
        self.g.add((self.CG.hasName, RDFS.range, XSD.string))
        self.g.add((self.CG.hasName, RDFS.label, Literal("has name")))

        # hasDescription - component has a description
        self.g.add((self.CG.hasDescription, RDF.type, OWL.DatatypeProperty))
        self.g.add((self.CG.hasDescription, RDFS.domain, self.CG.Component))
        self.g.add((self.CG.hasDescription, RDFS.range, XSD.string))
        self.g.add((self.CG.hasDescription, RDFS.label, Literal("has description")))

        # hasType - component has a type
        self.g.add((self.CG.hasType, RDF.type, OWL.DatatypeProperty))
        self.g.add((self.CG.hasType, RDFS.domain, self.CG.Component))
        self.g.add((self.CG.hasType, RDFS.range, XSD.string))
        self.g.add((self.CG.hasType, RDFS.label, Literal("has type")))

        # hasReturnType - method has a return type
        self.g.add((self.CODE.hasReturnType, RDF.type, OWL.DatatypeProperty))
        self.g.add((self.CODE.hasReturnType, RDFS.domain, self.CODE.Method))
        self.g.add((self.CODE.hasReturnType, RDFS.range, XSD.string))
        self.g.add((self.CODE.hasReturnType, RDFS.label, Literal("has return type")))

    def _define_individuals(self):
        """Define specific individuals and their relationships"""

        # Context individuals
        reverse_engineering_context = URIRef(self.RE.ReverseEngineeringContext)
        self.g.add((reverse_engineering_context, RDF.type, self.CG.Context))
        self.g.add(
            (
                reverse_engineering_context,
                RDFS.label,
                Literal("Reverse Engineering Context"),
            )
        )

        code_generation_context = URIRef(self.CG.CodeGenerationContext)
        self.g.add((code_generation_context, RDF.type, self.CG.Context))
        self.g.add((code_generation_context, RDFS.label, Literal("Code Generation Context")))

        # Format individuals
        list_format = URIRef(self.CG.ListFormat)
        self.g.add((list_format, RDF.type, self.CG.Format))
        self.g.add((list_format, RDFS.label, Literal("List Format")))

        dict_format = URIRef(self.CG.DictFormat)
        self.g.add((dict_format, RDF.type, self.CG.Format))
        self.g.add((dict_format, RDFS.label, Literal("Dict Format")))

        # Add format relationships
        self.g.add((reverse_engineering_context, self.CG.hasFormat, list_format))
        self.g.add((code_generation_context, self.CG.hasFormat, dict_format))

    def add_component(self, name: str, component_type: str, context: str, description: str = "") -> URIRef:
        """Add a component to the ontology"""

        # Create component URI
        component_uri = URIRef(f"{self.CG}{name}")

        # Add component to graph
        self.g.add((component_uri, RDF.type, self.CG.Component))
        self.g.add((component_uri, self.CG.hasName, Literal(name)))
        self.g.add((component_uri, self.CG.hasType, Literal(component_type)))
        self.g.add((component_uri, self.CG.hasDescription, Literal(description)))

        # Add context relationship
        if context == "reverse_engineering":
            self.g.add((component_uri, RDF.type, self.RE.ReverseEngineeringComponent))
            self.g.add(
                (
                    component_uri,
                    self.CG.hasContext,
                    URIRef(self.RE.ReverseEngineeringContext),
                )
            )
        elif context == "code_generation":
            self.g.add((component_uri, RDF.type, self.CG.CodeGenerationComponent))
            self.g.add(
                (
                    component_uri,
                    self.CG.hasContext,
                    URIRef(self.CG.CodeGenerationContext),
                )
            )

        return component_uri

    def add_method(
        self,
        component_uri: URIRef,
        method_name: str,
        return_type: str = "",
        parameters: List[Dict[str, str]] = None,
    ):
        """Add a method to a component"""

        # Create method URI
        method_uri = URIRef(f"{self.CODE}{method_name}")

        # Add method to graph
        self.g.add((method_uri, RDF.type, self.CODE.Method))
        self.g.add((method_uri, self.CG.hasName, Literal(method_name)))
        if return_type:
            self.g.add((method_uri, self.CODE.hasReturnType, Literal(return_type)))

        # Link method to component
        self.g.add((component_uri, self.CG.hasMethod, method_uri))

        # Add parameters if provided
        if parameters:
            for i, param in enumerate(parameters):
                param_uri = URIRef(f"{self.CODE}{method_name}_param_{i}")
                self.g.add((param_uri, RDF.type, self.CODE.Parameter))
                self.g.add(
                    (
                        param_uri,
                        self.CG.hasName,
                        Literal(param.get("name", f"param_{i}")),
                    )
                )
                if "type" in param:
                    self.g.add((param_uri, self.CG.hasType, Literal(param["type"])))
                self.g.add((method_uri, self.CODE.hasParameter, param_uri))

    def add_transformation_rule(self, from_component: URIRef, to_component: URIRef, rule_name: str):
        """Add a transformation rule between components"""

        # Create transformation rule
        rule_uri = URIRef(f"{self.CG}{rule_name}")
        self.g.add((rule_uri, RDF.type, OWL.ObjectProperty))
        self.g.add((rule_uri, RDFS.domain, from_component))
        self.g.add((rule_uri, RDFS.range, to_component))
        self.g.add((rule_uri, RDFS.label, Literal(rule_name)))

        # Add the transformation relationship
        self.g.add((from_component, rule_uri, to_component))

    def query_components_by_context(self, context: str) -> List[Dict[str, Any]]:
        """Query components by context using SPARQL"""

        if context == "reverse_engineering":
            context_uri = self.RE.ReverseEngineeringContext
            component_type = self.RE.ReverseEngineeringComponent
        elif context == "code_generation":
            context_uri = self.CG.CodeGenerationContext
            component_type = self.CG.CodeGenerationComponent
        else:
            return []

        # SPARQL query to find components in specific context
        query = """
        PREFIX cg: <http://example.org/code-generation#>
        PREFIX re: <http://example.org/reverse-engineering#>
        PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
        
        SELECT ?component ?name ?type ?description
        WHERE {
            ?component a ?componentType .
            ?component cg:hasName ?name .
            ?component cg:hasType ?type .
            ?component cg:hasDescription ?description .
            ?component cg:hasContext ?context .
            FILTER(?context = <%s>)
            FILTER(?componentType = <%s>)
        }
        """ % (
            context_uri,
            component_type,
        )

        results = []
        for row in self.g.query(query):
            results.append(
                {
                    "component": str(row.component),
                    "name": str(row.name),
                    "type": str(row.type),
                    "description": str(row.description),
                }
            )

        return results

    def validate_transformation(self, from_data: Any, to_format: str) -> Dict[str, Any]:
        """Validate transformation using ontological reasoning"""

        # Identify source concept based on data structure
        source_concept = self._identify_source_concept(from_data)
        if not source_concept:
            return {"valid": False, "errors": ["Could not identify source concept"]}

        # Find target concept
        target_concept = self._find_target_concept(to_format)
        if not target_concept:
            return {
                "valid": False,
                "errors": [f"No target concept found for format: {to_format}"],
            }

        # Check if transformation is allowed by ontology
        transformation_allowed = self._check_transformation_allowed(source_concept, target_concept)

        if transformation_allowed:
            return {
                "valid": True,
                "transformation_path": [source_concept, target_concept],
            }
        else:
            return {
                "valid": False,
                "errors": ["Transformation not allowed by ontology"],
            }

    def _identify_source_concept(self, data: Any) -> Optional[str]:
        """Identify source concept using ontological reasoning"""

        if isinstance(data, dict) and "components" in data:
            components = data["components"]
            if isinstance(components, list):
                return "reverse_engineering"
            elif isinstance(components, dict):
                return "code_generation"

        return None

    def _find_target_concept(self, target_format: str) -> Optional[str]:
        """Find target concept based on format"""

        if target_format == "dict":
            return "code_generation"
        elif target_format == "list":
            return "reverse_engineering"

        return None

    def _check_transformation_allowed(self, source_concept: str, target_concept: str) -> bool:
        """Check if transformation is allowed by ontology rules"""

        # Query the ontology to see if transformation is allowed
        if source_concept == "reverse_engineering" and target_concept == "code_generation":
            # Check if reverse engineering components can transform to code generation components
            query = """
            PREFIX re: <http://example.org/reverse-engineering#>
            PREFIX cg: <http://example.org/code-generation#>
            
            ASK {
                ?reComponent a re:ReverseEngineeringComponent .
                ?cgComponent a cg:CodeGenerationComponent .
                ?reComponent re:transformsTo ?cgComponent .
            }
            """
            result = bool(self.g.query(query))

            # If the specific relationship doesn't exist, check if the transformation rule exists
            if not result:
                # Check if there's a transformation rule that allows this
                query2 = """
                PREFIX re: <http://example.org/reverse-engineering#>
                PREFIX cg: <http://example.org/code-generation#>
                
                ASK {
                    ?reContext a cg:Context .
                    ?reContext rdfs:label "Reverse Engineering Context" .
                    ?cgContext a cg:Context .
                    ?cgContext rdfs:label "Code Generation Context" .
                }
                """
                result = bool(self.g.query(query2))

            return result

        return False

    def save_to_file(self, filepath: str, format: str = "turtle"):
        """Save ontology to file in specified format"""

        # Serialize the graph
        if format == "turtle":
            self.g.serialize(filepath, format="turtle")
        elif format == "xml":
            self.g.serialize(filepath, format="xml")
        elif format == "json-ld":
            self.g.serialize(filepath, format="json-ld")
        else:
            raise ValueError(f"Unsupported format: {format}")

    def load_from_file(self, filepath: str, format: str = "turtle"):
        """Load ontology from file"""

        # Parse the file
        if format == "turtle":
            self.g.parse(filepath, format="turtle")
        elif format == "xml":
            self.g.parse(filepath, format="xml")
        elif format == "json-ld":
            self.g.parse(filepath, format="json-ld")
        else:
            raise ValueError(f"Unsupported format: {format}")

    def get_statistics(self) -> Dict[str, Any]:
        """Get ontology statistics"""

        # Count different types of entities
        class_count = len(list(self.g.subjects(RDF.type, OWL.Class)))
        object_property_count = len(list(self.g.subjects(RDF.type, OWL.ObjectProperty)))
        datatype_property_count = len(list(self.g.subjects(RDF.type, OWL.DatatypeProperty)))
        individual_count = len(list(self.g.subjects(RDF.type, self.CG.Component)))

        return {
            "classes": class_count,
            "object_properties": object_property_count,
            "datatype_properties": datatype_property_count,
            "components": individual_count,
            "total_triples": len(self.g),
        }


def main():
    """Test the proper ontological system"""
    print("🏗️ Building Proper RDF/OWL Ontology for Code Generation Domain")
    print("=" * 70)

    # Create ontology
    ontology = ProperCodeGenerationOntology()

    # Add some components
    print("\n📚 Adding components to ontology...")

    # Add reverse engineering components
    quality_rule_re = ontology.add_component(
        "QualityRule",
        "class",
        "reverse_engineering",
        "Represents a code quality rule with detection and fix strategies",
    )

    ast_analyzer_re = ontology.add_component(
        "ASTAnalyzer",
        "class",
        "reverse_engineering",
        "AST-based code analyzer with quality rule integration",
    )

    # Add methods to components
    ontology.add_method(
        quality_rule_re,
        "detect_violations",
        "List[str]",
        [{"name": "code", "type": "str"}],
    )

    ontology.add_method(quality_rule_re, "generate_fix", "str", [{"name": "code", "type": "str"}])

    ontology.add_method(
        ast_analyzer_re,
        "analyze_file",
        "Dict[str, Any]",
        [{"name": "file_path", "type": "str"}],
    )

    # Add transformation rules
    print("🔄 Adding transformation rules...")
    ontology.add_transformation_rule(quality_rule_re, URIRef(f"{ontology.CG}QualityRule"), "transformsTo")

    # Query components by context
    print("\n🔍 Querying components by context...")
    re_components = ontology.query_components_by_context("reverse_engineering")
    print(f"  Reverse Engineering Components: {len(re_components)}")
    for comp in re_components:
        print(f"    • {comp['name']}: {comp['description']}")

    # Test transformation validation
    print("\n✅ Testing transformation validation...")
    test_data = {"components": [{"name": "QualityRule", "type": "class"}]}
    validation = ontology.validate_transformation(test_data, "dict")
    print(f"  List -> Dict validation: {'✅ PASS' if validation['valid'] else '❌ FAIL'}")

    # Get ontology statistics
    stats = ontology.get_statistics()
    print(f"\n📊 Ontology Statistics:")
    print(f"  Classes: {stats['classes']}")
    print(f"  Object Properties: {stats['object_properties']}")
    print(f"  Data Properties: {stats['datatype_properties']}")
    print(f"  Components: {stats['components']}")
    print(f"  Total Triples: {stats['total_triples']}")

    # Save ontology in multiple formats
    print(f"\n💾 Saving ontology...")
    ontology.save_to_file("code_generation_ontology.ttl", "turtle")
    ontology.save_to_file("code_generation_ontology.xml", "xml")
    ontology.save_to_file("code_generation_ontology.json", "json-ld")

    print(f"  ✅ Turtle: code_generation_ontology.ttl")
    print(f"  ✅ XML: code_generation_ontology.xml")
    print(f"  ✅ JSON-LD: code_generation_ontology.json")

    print(f"\n🎉 Proper ontological system ready!")
    print(f"📋 Capabilities:")
    print(f"  • RDF/OWL formal ontology")
    print(f"  • SPARQL queries")
    print(f"  • Ontological reasoning")
    print(f"  • Multiple serialization formats")
    print(f"  • Proper ontological validation")


if __name__ == "__main__":
    main()
